init:
  - git config --global core.autocrlf true

version: 1.1.0.{build}

configuration: Release

cache:
- packages -> **\packages.config
- '%USERPROFILE%\.nuget\packages -> **\project.json'


assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

services:
- mssql2012sp1
#- mysql
#- postgresql

before_build:
- cmd: dotnet restore 

build:
  project: LinqToDB.Identity.sln
  verbosity: minimal

after_build:
- cmd: dotnet pack --no-build src/LinqToDB.Identity/project.json --version-suffix=beta%APPVEYOR_BUILD_NUMBER% -c=Release

before_test:
- ps: |
    [Environment]::SetEnvironmentVariable("Test:SqlServer:DefaultConnectionString", "Server=(local)\SQL2012SP1;Database=master;Integrated Security=true", "Machine")
    [Environment]::SetEnvironmentVariable("Test:SqlServer:DefaultConnectionString", "Server=(local)\SQL2012SP1;Database=master;Integrated Security=true")

test_script:
- ps: |
    Write-Host "Connection string"
    Write-Host $([Environment]::GetEnvironmentVariable("Test:SqlServer:DefaultConnectionString"))
    dotnet test test\Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test -c Release -f netcoreapp1.0 
    $test1res = $LASTEXITCODE 
    # upload results to AppVeyor
    #$wc = New-Object 'System.Net.WebClient'
    #$wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))
    dotnet test test\Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test -c Release -f netcoreapp1.0 
    $test2res = $LASTEXITCODE 
    # upload results to AppVeyor
    #$wc = New-Object 'System.Net.WebClient'
    #$wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))
    IF ($test1res -ne 0 -or $test2res -ne 0) { exit $LASTEXITCODE }

artifacts:
- path: src\**\*.nupkg

deploy:
- provider: NuGet
  server: https://www.myget.org/F/ili/api/v2
  api_key:
    secure: pFvgey1/w68ZvVHFN/GWZdDFjSABpBRfb0XfLnW3wvhlfyEUiSyfr3dAUcbmlpsk
  skip_symbols: true